services:
  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:5432 && python main.py"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/redis:/data

  worker:
    restart: always
    build: .
    command: >
      sh -c "celery -A tasks worker -l info"
    depends_on:
      - redis
      - web

  beat:
    restart: always
    build: .
    command: >
      sh -c "celery -A tasks beat -l info"
    depends_on:
      - redis
      - web
      - worker